# Generated by Django 5.1.15 on 2026-02-22 14:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
        ('flows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform_user_id', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_users', to='bots.bot')),
                ('current_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flows.flownode')),
            ],
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='bots.bot')),
                ('chat_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='messaging.chatuser')),
                ('flow_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flows.flownode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('content_type', models.CharField(default='text', max_length=20)),
                ('content', models.JSONField(default=dict)),
                ('platform_message_id', models.CharField(blank=True, max_length=255)),
                ('is_error', models.BooleanField(default=False)),
                ('error_detail', models.TextField(blank=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bots.bot')),
                ('chat_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.chatuser')),
                ('flow_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flows.flownode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='chatuser',
            constraint=models.UniqueConstraint(fields=('bot', 'platform_user_id'), name='unique_chat_user_per_bot'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['bot', 'created_at'], name='messaging_m_bot_id_80edca_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat_user', 'created_at'], name='messaging_m_chat_us_f6e24e_idx'),
        ),
    ]
