# Generated by Django 5.1.15 on 2026-02-22 14:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('viber', 'Viber'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('error', 'Error')], default='draft', max_length=20)),
                ('api_token_encrypted', models.TextField(blank=True)),
                ('webhook_url', models.URLField(blank=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=128)),
                ('welcome_message', models.TextField(blank=True, default='Hello! How can I help you?')),
                ('fallback_message', models.TextField(blank=True, default="I didn't understand that. Please try again.")),
                ('is_active', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='unique_bot_name_per_owner')],
            },
        ),
    ]
